name: Robin AI Reviewer

on:
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Robin AI Reviewer
        uses: Integral-Healthcare/robin-ai-reviewer@v1.4.0
        with:
          GITHUB_TOKEN: "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"
          OPEN_AI_API_KEY: "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"
          files_to_ignore: |
            "README.md"
            "assets/*"
            "package-lock.json"
